// src/views/UnitView.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { unitService } from '@/services/unitService'
import type { Unit } from '@/types/unit'
import UnitCardContent from '@/components/UnitCardContent.vue'
import OpponentList from '@/components/OpponentList.vue'

const route = useRoute()
const router = useRouter()

const unit = ref<Unit | undefined>(undefined)

const filterForm = ref<{ [key: string]: boolean }>({
  egyptian: true,
  greek: true,
  norse: true
})

onMounted(() => {
  const unitName = route.params.unitName as string
  unit.value = unitService.getByName(unitName)

  if (!unit.value) {
    router.push({ name: 'home' })
  }
})

const filteredUnitsBeatenByMe = computed((): Unit[] => {
  if (!unit.value) return []
  const basis = unitService.getUnitsBeatenBy(unit.value)
  return basis.filter((u) => filterForm.value[u.race])
})

const filteredUnitsThatBeatMe = computed((): Unit[] => {
  if (!unit.value) return []
  const basis = unitService.getUnitsThatBeat(unit.value)
  return basis.filter((u) => filterForm.value[u.race])
})
</script>

<template>
  <div v-if="unit">
    <h1 class="near-white">
      <router-link to="/" class="link white">&larr;</router-link>
      {{ unit.name }}
      <span class="pa1 mt--1 bg-white black tc b dib w2">{{ unit.baseDice }}</span>
    </h1>

    <div class="dib ph3 mb3" :class="unit.race">
      <UnitCardContent :hide="['header', 'cost']" :unit="unit" />
    </div>

    <table class="collapse">
      <thead>
        <tr>
          <th class="bg-near-white pa2">Filter</th>
          <td class="bg-near-white pa2">
            <label
              v-for="race in ['egyptian', 'greek', 'norse']"
              :key="race"
              v-show="unit.race !== race"
              class="mh2"
            >
              <input type="checkbox" v-model="filterForm[race]" />
              {{ race.charAt(0).toUpperCase() + race.slice(1) }}
            </label>
          </td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class="h5 bg-light-gray">
            <p class="rotate-270">Strong vs</p>
          </th>
          <td class="bg-light-gray">
            <div>
              <OpponentList :opponents="filteredUnitsBeatenByMe" />
            </div>
          </td>
        </tr>
        <tr>
          <th class="h5 bg-moon-gray">
            <p class="rotate-270">Weak vs</p>
          </th>
          <td class="bg-moon-gray">
            <div>
              <OpponentList :opponents="filteredUnitsThatBeatMe" />
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// angular/src/app/army/unit-view/unit-view.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { Unit } from 'app/army/unit';
import { UnitService } from 'app/army/unit.service';

@Component({
  selector: 'aom-unit-view',
  templateUrl: './unit-view.component.html',
  styleUrls: ['./unit-view.component.css']
})
export class UnitViewComponent implements OnInit {

  @Input("unit") unit : Unit;
  
  filterForm = new FormGroup({
    "egyptian" : new FormControl(true),
    "greek" : new FormControl(true),
    "norse" : new FormControl(true)
  });

  constructor(public unitService : UnitService) { 
  }

  ngOnInit(): void {
  }

  filteredUnitsBeatenByMe() : Unit[] {
    const basis = this.unitService.getUnitsBeatenBy(this.unit);
    return basis.filter(u => this.filterForm.value[u.race]);
  }
  
  filteredUnitsThatBeatMe() : Unit[] {
    const basis = this.unitService.getUnitsThatBeat(this.unit);
    return basis.filter(u => this.filterForm.value[u.race]);
  }

}

<div>
    <h1 class="near-white">
        <a class="link white" uiSref="home">&larr;</a>
        {{unit.name}}
        <span class="pa1 mt--1 bg-white black tc b dib w2">{{unit.baseDice}}</span>
    </h1>

    <div class="dib ph3 mb3" [class]="unit.race">
        <aom-unit-card-content [hide]="['header', 'cost']" [unit]="unit">
        </aom-unit-card-content>
    </div>

    <table class="collapse">
        <thead>
            <tr>
                <th class="bg-near-white pa2">Filter</th>
                <td class="bg-near-white pa2">
                    <form [formGroup]="filterForm">
                        <ng-container *ngFor="let thisRace of ['egyptian', 'greek', 'norse']">
                            <label class="mh2" *ngIf="unit.race !== thisRace">
                                <input type="checkbox" [formControlName]="thisRace">{{thisRace | titlecase}}</label>
                        </ng-container>
                    </form>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th class="h5 bg-light-gray">
                    <p class="rotate-270">Strong vs</p>
                </th>
                <td class="bg-light-gray">
                    <div>
                        <aom-opponent-list [opponents]="filteredUnitsBeatenByMe()"></aom-opponent-list>
                    </div>
                </td>
            </tr>
            <tr>
                <th class="h5 bg-moon-gray">
                    <p class="rotate-270">Weak vs</p>
                </th>
                <td class="bg-moon-gray">
                    <div>
                        <aom-opponent-list [opponents]="filteredUnitsThatBeatMe()"></aom-opponent-list>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
