// src/app/army/unit-view/unit-view.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Unit } from 'app/army/unit';
import { UnitService } from 'app/army/unit.service';

@Component({
  selector: 'aom-unit-view',
  templateUrl: './unit-view.component.html',
  styleUrls: ['./unit-view.component.css']
})
export class UnitViewComponent implements OnInit {

  @Input("unit") unit : Unit;

  constructor(public unitService : UnitService) { 
  }

  ngOnInit(): void {
  }
  
}

<div class="">

    <div class="center pv2">
        <form>
            <fieldset class="ba b--transparent ph0 mh0">
                <legend class="tc f4 fw6"><u>{{unit.baseDice}}</u> {{unit.name}}
                </legend>

                <div class="">
                    <aom-unit-card-content [hide]="['header', 'cost']" [unit]="unit">
                    </aom-unit-card-content>
                </div>
                <div class="pv2 tc center disabled">
                    <label class="mh2"><input type="checkbox" disabled checked>Egyptian</label>
                    <label class="mh2"><input type="checkbox" disabled checked>Greek</label>
                    <label class="mh2"><input type="checkbox" disabled checked>Norse</label>
                </div>
                <table class="collapse">
                    <tbody>
                        <tr>
                            <th class="h5 bg-light-gray">
                                <p class="rotate-270">Strong vs</p>
                            </th>
                            <td class="bg-light-gray">
                                <!-- TODO make carousel component -->
                                <div><!-- class="overflow-x-scroll" -->
                                    <div class="w5 dib ba b--black pa1 ma1"
                                        *ngFor="let enemy of unitService.getUnitsBeatenBy(unit)"
                                        [class]="enemy.race">
                                        <aom-unit-card-content [hide]="['cost', 'bonuses', 'special']" [unit]="enemy">
                                        </aom-unit-card-content>
                                    </div>

                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th class="h5 bg-moon-gray">
                                <p class="rotate-270">Weak vs</p>
                            </th>
                            <td class="bg-moon-gray">
                                <!-- TODO make carousel component -->
                                <div><!-- class="overflow-x-scroll" -->
                                    <div class="w5 dib ba b--black pa1 ma1"
                                        *ngFor="let enemy of unitService.getUnitsThatBeat(unit)"
                                        [class]="enemy.race">
                                        <aom-unit-card-content [hide]="['cost', 'special']" [unit]="enemy">
                                        </aom-unit-card-content>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>

                </table>
                <div class="flex">


                </div>
            </fieldset>
        </form>
    </div>
</div>

// src/views/UnitView.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { unitService } from '@/services/unitService'
import type { Unit } from '@/types/unit'
import UnitCardContent from '@/components/UnitCardContent.vue'
import OpponentList from '@/components/OpponentList.vue'

const route = useRoute()
const router = useRouter()

const unit = ref<Unit | undefined>(undefined)

const filterForm = ref<{ [key: string]: boolean }>({
  egyptian: true,
  greek: true,
  norse: true
})

onMounted(() => {
  const unitName = route.params.unitName as string
  unit.value = unitService.getByName(unitName)

  if (!unit.value) {
    router.push({ name: 'home' })
  }
})

const filteredUnitsBeatenByMe = computed((): Unit[] => {
  if (!unit.value) return []
  const basis = unitService.getUnitsBeatenBy(unit.value)
  return basis.filter((u) => filterForm.value[u.race])
})

const filteredUnitsThatBeatMe = computed((): Unit[] => {
  if (!unit.value) return []
  const basis = unitService.getUnitsThatBeat(unit.value)
  return basis.filter((u) => filterForm.value[u.race])
})
</script>

<template>
  <div v-if="unit">
    <h1 class="near-white">
      <router-link to="/" class="link white">&larr;</router-link>
      {{ unit.name }}
      <span class="pa1 mt--1 bg-white black tc b dib w2">{{ unit.baseDice }}</span>
    </h1>

    <div class="dib ph3 mb3" :class="unit.race">
      <UnitCardContent :hide="['header', 'cost']" :unit="unit" />
    </div>

    <table class="collapse">
      <thead>
        <tr>
          <th class="bg-near-white pa2">Filter</th>
          <td class="bg-near-white pa2">
            <label
              v-for="race in ['egyptian', 'greek', 'norse']"
              :key="race"
              v-show="unit.race !== race"
              class="mh2"
            >
              <input type="checkbox" v-model="filterForm[race]" />
              {{ race.charAt(0).toUpperCase() + race.slice(1) }}
            </label>
          </td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class="h5 bg-light-gray">
            <p class="rotate-270">Strong vs</p>
          </th>
          <td class="bg-light-gray">
            <div>
              <OpponentList :opponents="filteredUnitsBeatenByMe" />
            </div>
          </td>
        </tr>
        <tr>
          <th class="h5 bg-moon-gray">
            <p class="rotate-270">Weak vs</p>
          </th>
          <td class="bg-moon-gray">
            <div>
              <OpponentList :opponents="filteredUnitsThatBeatMe" />
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
