// vue/src/components/OpponentList.vue
<script setup lang="ts">
import type { Unit } from '@/types/unit'
import UnitCardContent from './UnitCardContent.vue'

defineProps<{
  opponents: Unit[]
}>()
</script>

<template>
  <div v-for="enemy in opponents" :key="enemy.name" class="w5 dib ba b--black pa1 ma1" :class="enemy.race">
    <UnitCardContent :hide="['cost', 'bonuses', 'special']" :unit="enemy" />
  </div>
</template>

<style scoped>
.egyptian {
  background-color: #ffeaa7;
}

.greek {
  background-color: #74b9ff;
}

.norse {
  background-color: #a29bfe;
}
</style>

// src/app/army/opponent-list/opponent-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Unit } from 'app/army/unit';
import { UnitService } from 'app/army/unit.service';

@Component({
  selector: 'aom-opponent-list',
  templateUrl: './opponent-list.component.html',
  styleUrls: ['./opponent-list.component.css']
})
export class OpponentListComponent implements OnInit {

  @Input("opponents") opponents : Unit[];

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="w5 dib ba b--black pa1 ma1" *ngFor="let enemy of opponents" [class]="enemy.race">
    <aom-unit-card-content [hide]="['cost', 'bonuses', 'special']" [unit]="enemy">
    </aom-unit-card-content>
</div>
